version: '3'

services:
  web:
    build: ./web
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTSINER}
    ports:
      - 8000:80
    working_dir: ${APP_PATH_CONTSINER}     

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080    

  composer:
    image: composer
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTSINER}
    working_dir: ${APP_PATH_CONTSINER}
    command: composer install

  node:
    image: "node:10"
    user: "node"
    working_dir: ${APP_PATH_CONTSINER}
    volumes:
      - .${APP_PATH_HOST}:${APP_PATH_CONTSINER}
    expose:
      - "8081"
    command: npm install && npm run dev  