version: '3'

services:
  web:
    build: ./web
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTSINER}
    ports:
      - 8080:80
    working_dir: ${APP_PATH_CONTSINER}

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 6080:8080    

  composer:
    image: composer:1.6
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTSINER}
    working_dir: ${APP_PATH_CONTSINER}
    command: composer install

  node:
    image: "node:10"
    working_dir: ${APP_PATH_CONTSINER}
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTSINER}
